// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) 
// Source File Name:   IconFactory.java

package com.zbluesoftware.fsxp.graphics;

import java.util.HashMap;
import javax.swing.ImageIcon;

public class IconFactory
{

    private IconFactory()
    {
        iconHM = new HashMap();
        iconHM.put("delete", new ImageIcon(getClass().getResource("icons/delete.gif")));
        iconHM.put("cutLine", new ImageIcon(getClass().getResource("icons/CutLine.gif")));
        iconHM.put("ilsRunwayPrimary", new ImageIcon(getClass().getResource("icons/ILSRunwayPrimary.gif")));
        iconHM.put("ilsRunwaySecondary", new ImageIcon(getClass().getResource("icons/ILSRunwaySecondary.gif")));
        iconHM.put("fsxConnected", new ImageIcon(getClass().getResource("icons/FSXConnected.gif")));
        iconHM.put("fsxDisconnected", new ImageIcon(getClass().getResource("icons/FSXDisconnected.gif")));
        iconHM.put("padlockLocked", new ImageIcon(getClass().getResource("icons/PadlockLocked.gif")));
        iconHM.put("padlockUnlocked", new ImageIcon(getClass().getResource("icons/PadlockUnlocked.gif")));
        iconHM.put("highlightedTWPath", new ImageIcon(getClass().getResource("icons/HighlightedTWPath.gif")));
        iconHM.put("select", new ImageIcon(getClass().getResource("icons/Select.gif")));
        iconHM.put("selectOver", new ImageIcon(getClass().getResource("icons/SelectOver.gif")));
        iconHM.put("selectOn", new ImageIcon(getClass().getResource("icons/SelectOn.gif")));
        iconHM.put("parking16", new ImageIcon(getClass().getResource("icons/Parking16.gif")));
        iconHM.put("parking32", new ImageIcon(getClass().getResource("icons/Parking32.gif")));
        iconHM.put("parking", new ImageIcon(getClass().getResource("icons/Parking.gif")));
        iconHM.put("parkingOver", new ImageIcon(getClass().getResource("icons/ParkingOver.gif")));
        iconHM.put("parkingOn", new ImageIcon(getClass().getResource("icons/ParkingOn.gif")));
        iconHM.put("pGateLarge32", new ImageIcon(getClass().getResource("icons/PGateLarge32.png")));
        iconHM.put("pGateMedium32", new ImageIcon(getClass().getResource("icons/PGateMedium32.png")));
        iconHM.put("pGateSmall32", new ImageIcon(getClass().getResource("icons/PGateSmall32.png")));
        iconHM.put("pGeneralAviation32", new ImageIcon(getClass().getResource("icons/PGeneralAviation32.png")));
        iconHM.put("pGALarge32", new ImageIcon(getClass().getResource("icons/PGALarge32.png")));
        iconHM.put("pGAMedium32", new ImageIcon(getClass().getResource("icons/PGAMedium32.png")));
        iconHM.put("pGASmall32", new ImageIcon(getClass().getResource("icons/PGASmall32.png")));
        iconHM.put("pCargo32", new ImageIcon(getClass().getResource("icons/PCargo32.png")));
        iconHM.put("pMilitary32", new ImageIcon(getClass().getResource("icons/PMilitary32.png")));
        iconHM.put("pMilitaryCargo32", new ImageIcon(getClass().getResource("icons/PMilitaryCargo32.png")));
        iconHM.put("pVehicle32", new ImageIcon(getClass().getResource("icons/PVehicle32.png")));
        iconHM.put("pDock32", new ImageIcon(getClass().getResource("icons/PDock32.png")));
        iconHM.put("pFuel32", new ImageIcon(getClass().getResource("icons/PFuel32.png")));
        iconHM.put("taxiPoint16", new ImageIcon(getClass().getResource("icons/TWPoint16.jpg")));
        iconHM.put("taxiPoint32", new ImageIcon(getClass().getResource("icons/TWPoint32.gif")));
        iconHM.put("taxiPoint", new ImageIcon(getClass().getResource("icons/TaxiPoint.gif")));
        iconHM.put("taxiPointOver", new ImageIcon(getClass().getResource("icons/TaxiPointOver.gif")));
        iconHM.put("taxiPointOn", new ImageIcon(getClass().getResource("icons/TaxiPointOn.gif")));
        iconHM.put("taxiway16", new ImageIcon(getClass().getResource("icons/Taxiway16.gif")));
        iconHM.put("taxiway32", new ImageIcon(getClass().getResource("icons/Taxiway32.gif")));
        iconHM.put("taxiwayJPG", new ImageIcon(getClass().getResource("icons/Taxiway32.jpg")));
        iconHM.put("taxiway", new ImageIcon(getClass().getResource("icons/Taxiway.gif")));
        iconHM.put("taxiwayOver", new ImageIcon(getClass().getResource("icons/TaxiwayOver.gif")));
        iconHM.put("taxiwayOn", new ImageIcon(getClass().getResource("icons/TaxiwayOn.gif")));
        iconHM.put("apron16", new ImageIcon(getClass().getResource("icons/Apron16.gif")));
        iconHM.put("apron32", new ImageIcon(getClass().getResource("icons/Apron32.gif")));
        iconHM.put("apron", new ImageIcon(getClass().getResource("icons/Apron.gif")));
        iconHM.put("apronOver", new ImageIcon(getClass().getResource("icons/ApronOver.gif")));
        iconHM.put("apronOn", new ImageIcon(getClass().getResource("icons/ApronOn.gif")));
        iconHM.put("ilsTaxiPoint16", new ImageIcon(getClass().getResource("icons/ILSTaxiPoint16.jpg")));
        iconHM.put("ilsTaxiPoint32", new ImageIcon(getClass().getResource("icons/ILSTaxiPoint32.gif")));
        iconHM.put("ilsTaxiPoint", new ImageIcon(getClass().getResource("icons/ILSTaxiPoint.gif")));
        iconHM.put("ilsTaxiPointOver", new ImageIcon(getClass().getResource("icons/ILSTaxiPointOver.gif")));
        iconHM.put("ilsTaxiPointOn", new ImageIcon(getClass().getResource("icons/ILSTaxiPointOn.gif")));
        iconHM.put("hsTaxiPoint16", new ImageIcon(getClass().getResource("icons/HSTaxiPoint16.jpg")));
        iconHM.put("hsTaxiPoint32", new ImageIcon(getClass().getResource("icons/HSTaxiPoint32.gif")));
        iconHM.put("hsTaxiPoint", new ImageIcon(getClass().getResource("icons/HSTaxiPoint.gif")));
        iconHM.put("hsTaxiPointOver", new ImageIcon(getClass().getResource("icons/HSTaxiPointOver.gif")));
        iconHM.put("hsTaxiPointOn", new ImageIcon(getClass().getResource("icons/HSTaxiPointOn.gif")));
        iconHM.put("startPoint16", new ImageIcon(getClass().getResource("icons/StartPoint16.gif")));
        iconHM.put("startPoint32", new ImageIcon(getClass().getResource("icons/StartPoint32.gif")));
        iconHM.put("startPoint", new ImageIcon(getClass().getResource("icons/StartPoint.gif")));
        iconHM.put("startPointOver", new ImageIcon(getClass().getResource("icons/StartPointOver.gif")));
        iconHM.put("startPointOn", new ImageIcon(getClass().getResource("icons/StartPointOn.gif")));
        iconHM.put("tower16", new ImageIcon(getClass().getResource("icons/Tower16.jpg")));
        iconHM.put("tower", new ImageIcon(getClass().getResource("icons/Tower.gif")));
        iconHM.put("towerOver", new ImageIcon(getClass().getResource("icons/TowerOver.gif")));
        iconHM.put("towerOn", new ImageIcon(getClass().getResource("icons/TowerOn.gif")));
        iconHM.put("taxiwaySign16", new ImageIcon(getClass().getResource("icons/TaxiwaySign16.gif")));
        iconHM.put("taxiwaySign32", new ImageIcon(getClass().getResource("icons/TaxiwaySign32.gif")));
        iconHM.put("taxiwaySign", new ImageIcon(getClass().getResource("icons/TaxiwaySign.gif")));
        iconHM.put("taxiwaySignOver", new ImageIcon(getClass().getResource("icons/TaxiwaySignOver.gif")));
        iconHM.put("taxiwaySignOn", new ImageIcon(getClass().getResource("icons/TaxiwaySignOn.gif")));
        iconHM.put("apronEdgeLight", new ImageIcon(getClass().getResource("icons/ApronEdgeLight.gif")));
        iconHM.put("apronEdgeLightOver", new ImageIcon(getClass().getResource("icons/ApronEdgeLightOver.gif")));
        iconHM.put("apronEdgeLightOn", new ImageIcon(getClass().getResource("icons/ApronEdgeLightOn.gif")));
        iconHM.put("helipad16", new ImageIcon(getClass().getResource("icons/Helipad16.gif")));
        iconHM.put("helipad", new ImageIcon(getClass().getResource("icons/Helipad.gif")));
        iconHM.put("helipadOver", new ImageIcon(getClass().getResource("icons/HelipadOver.gif")));
        iconHM.put("helipadOn", new ImageIcon(getClass().getResource("icons/HelipadOn.gif")));
        iconHM.put("runway16", new ImageIcon(getClass().getResource("icons/Runway16.gif")));
        iconHM.put("runway32", new ImageIcon(getClass().getResource("icons/Runway32.gif")));
        iconHM.put("runwayJPG", new ImageIcon(getClass().getResource("icons/Runway32.jpg")));
        iconHM.put("runway", new ImageIcon(getClass().getResource("icons/Runway.gif")));
        iconHM.put("runwayOver", new ImageIcon(getClass().getResource("icons/RunwayOver.gif")));
        iconHM.put("runwayOn", new ImageIcon(getClass().getResource("icons/RunwayOn.gif")));
        iconHM.put("fence", new ImageIcon(getClass().getResource("icons/Fence.gif")));
        iconHM.put("fenceOver", new ImageIcon(getClass().getResource("icons/FenceOver.gif")));
        iconHM.put("fenceOn", new ImageIcon(getClass().getResource("icons/FenceOn.gif")));
        iconHM.put("scroll", new ImageIcon(getClass().getResource("icons/Scroll.gif")));
        iconHM.put("scrollOver", new ImageIcon(getClass().getResource("icons/ScrollOver.gif")));
        iconHM.put("scrollOn", new ImageIcon(getClass().getResource("icons/ScrollOn.gif")));
        iconHM.put("zoomIn16", new ImageIcon(getClass().getResource("icons/ZoomIn16.gif")));
        iconHM.put("zoomIn", new ImageIcon(getClass().getResource("icons/ZoomIn.gif")));
        iconHM.put("zoomInOver", new ImageIcon(getClass().getResource("icons/ZoomInOver.gif")));
        iconHM.put("zoomInOn", new ImageIcon(getClass().getResource("icons/ZoomInOn.gif")));
        iconHM.put("zoomOut16", new ImageIcon(getClass().getResource("icons/ZoomOut16.gif")));
        iconHM.put("zoomOut", new ImageIcon(getClass().getResource("icons/ZoomOut.gif")));
        iconHM.put("zoomOutOver", new ImageIcon(getClass().getResource("icons/ZoomOutOver.gif")));
        iconHM.put("zoomOutOn", new ImageIcon(getClass().getResource("icons/ZoomOutOn.gif")));
        iconHM.put("blastFence", new ImageIcon(getClass().getResource("icons/BlastFence.gif")));
        iconHM.put("blastFenceOver", new ImageIcon(getClass().getResource("icons/BlastFenceOver.gif")));
        iconHM.put("blastFenceOn", new ImageIcon(getClass().getResource("icons/BlastFenceOn.gif")));
        iconHM.put("jetway", new ImageIcon(getClass().getResource("icons/Jetway.gif")));
        iconHM.put("jetwayOver", new ImageIcon(getClass().getResource("icons/JetwayOver.gif")));
        iconHM.put("jetwayOn", new ImageIcon(getClass().getResource("icons/JetwayOn.gif")));
        iconHM.put("ilsBeam", new ImageIcon(getClass().getResource("icons/ILSBeam.gif")));
        iconHM.put("ilsBeamOver", new ImageIcon(getClass().getResource("icons/ILSBeamOver.gif")));
        iconHM.put("ilsBeamOn", new ImageIcon(getClass().getResource("icons/ILSBeamOn.gif")));
        iconHM.put("marker", new ImageIcon(getClass().getResource("icons/Marker.gif")));
        iconHM.put("markerOver", new ImageIcon(getClass().getResource("icons/MarkerOver.gif")));
        iconHM.put("markerOn", new ImageIcon(getClass().getResource("icons/MarkerOn.gif")));
        iconHM.put("vor", new ImageIcon(getClass().getResource("icons/VOR.gif")));
        iconHM.put("vorOver", new ImageIcon(getClass().getResource("icons/VOROver.gif")));
        iconHM.put("vorOn", new ImageIcon(getClass().getResource("icons/VOROn.gif")));
        iconHM.put("ndb", new ImageIcon(getClass().getResource("icons/NDB.gif")));
        iconHM.put("ndbOver", new ImageIcon(getClass().getResource("icons/NDBOver.gif")));
        iconHM.put("ndbOn", new ImageIcon(getClass().getResource("icons/NDBOn.gif")));
        iconHM.put("windsock", new ImageIcon(getClass().getResource("icons/Windsock.gif")));
        iconHM.put("windsockOver", new ImageIcon(getClass().getResource("icons/WindsockOver.gif")));
        iconHM.put("windsockOn", new ImageIcon(getClass().getResource("icons/WindsockOn.gif")));
        iconHM.put("exclude16", new ImageIcon(getClass().getResource("icons/Exclude16.gif")));
        iconHM.put("exclude32", new ImageIcon(getClass().getResource("icons/Exclude32.gif")));
        iconHM.put("exclude", new ImageIcon(getClass().getResource("icons/Exclude.gif")));
        iconHM.put("excludeOver", new ImageIcon(getClass().getResource("icons/ExcludeOver.gif")));
        iconHM.put("excludeOn", new ImageIcon(getClass().getResource("icons/ExcludeOn.gif")));
        iconHM.put("fuel16", new ImageIcon(getClass().getResource("icons/Fuel16.gif")));
        iconHM.put("fuel32", new ImageIcon(getClass().getResource("icons/Fuel32.gif")));
        iconHM.put("fuel", new ImageIcon(getClass().getResource("icons/Fuel.gif")));
        iconHM.put("fuelOver", new ImageIcon(getClass().getResource("icons/FuelOver.gif")));
        iconHM.put("fuelOn", new ImageIcon(getClass().getResource("icons/FuelOn.gif")));
        iconHM.put("scenery16", new ImageIcon(getClass().getResource("icons/Scenery16.gif")));
        iconHM.put("scenery32", new ImageIcon(getClass().getResource("icons/Scenery32.gif")));
        iconHM.put("scenery", new ImageIcon(getClass().getResource("icons/Scenery.gif")));
        iconHM.put("sceneryOver", new ImageIcon(getClass().getResource("icons/SceneryOver.gif")));
        iconHM.put("sceneryOn", new ImageIcon(getClass().getResource("icons/SceneryOn.gif")));
        iconHM.put("cut16", new ImageIcon(getClass().getResource("icons/Cut16.gif")));
        iconHM.put("cut32", new ImageIcon(getClass().getResource("icons/Cut32.gif")));
        iconHM.put("copy16", new ImageIcon(getClass().getResource("icons/Copy16.gif")));
        iconHM.put("copy32", new ImageIcon(getClass().getResource("icons/Copy32.gif")));
        iconHM.put("paste16", new ImageIcon(getClass().getResource("icons/Paste16.gif")));
        iconHM.put("paste32", new ImageIcon(getClass().getResource("icons/Paste32.gif")));
        iconHM.put("undo16", new ImageIcon(getClass().getResource("icons/Undo16.gif")));
        iconHM.put("undo32", new ImageIcon(getClass().getResource("icons/Undo32.gif")));
        iconHM.put("redo16", new ImageIcon(getClass().getResource("icons/Redo16.gif")));
        iconHM.put("redo32", new ImageIcon(getClass().getResource("icons/Redo32.gif")));
        iconHM.put("history16", new ImageIcon(getClass().getResource("icons/History16.gif")));
        iconHM.put("history32", new ImageIcon(getClass().getResource("icons/History32.png")));
        iconHM.put("com16", new ImageIcon(getClass().getResource("icons/Com16.gif")));
        iconHM.put("com32", new ImageIcon(getClass().getResource("icons/Com32.gif")));
        iconHM.put("approach16", new ImageIcon(getClass().getResource("icons/Approach16.gif")));
        iconHM.put("approach32", new ImageIcon(getClass().getResource("icons/Approach32.gif")));
        iconHM.put("lighting16", new ImageIcon(getClass().getResource("icons/Lighting16.png")));
        iconHM.put("lighting32", new ImageIcon(getClass().getResource("icons/Lighting32.png")));
        iconHM.put("center16", new ImageIcon(getClass().getResource("icons/Center16.gif")));
        iconHM.put("center32", new ImageIcon(getClass().getResource("icons/Center32.gif")));
        iconHM.put("padlock16", new ImageIcon(getClass().getResource("icons/Padlock16.gif")));
        iconHM.put("padlock32", new ImageIcon(getClass().getResource("icons/Padlock32.gif")));
        iconHM.put("counts16", new ImageIcon(getClass().getResource("icons/Counts16.gif")));
        iconHM.put("counts32", new ImageIcon(getClass().getResource("icons/Counts32.gif")));
        iconHM.put("background16", new ImageIcon(getClass().getResource("icons/Background16.gif")));
        iconHM.put("background32", new ImageIcon(getClass().getResource("icons/Background32.gif")));
        iconHM.put("taxiwayNames16", new ImageIcon(getClass().getResource("icons/TaxiwayNames16.gif")));
        iconHM.put("taxiwayNames32", new ImageIcon(getClass().getResource("icons/TaxiwayNames32.gif")));
        iconHM.put("services16", new ImageIcon(getClass().getResource("icons/Services16.gif")));
        iconHM.put("services32", new ImageIcon(getClass().getResource("icons/Services32.gif")));
        iconHM.put("moveAirport16", new ImageIcon(getClass().getResource("icons/MoveAirport16.gif")));
        iconHM.put("moveAirport32", new ImageIcon(getClass().getResource("icons/MoveAirport32.gif")));
        iconHM.put("rotate16", new ImageIcon(getClass().getResource("icons/Rotate16.png")));
        iconHM.put("rotate32", new ImageIcon(getClass().getResource("icons/Rotate32.png")));
        iconHM.put("connectionStatus16", new ImageIcon(getClass().getResource("icons/ConnectionStatus16.png")));
        iconHM.put("connectionStatus32", new ImageIcon(getClass().getResource("icons/ConnectionStatus32.png")));
        iconHM.put("planeMake16", new ImageIcon(getClass().getResource("icons/PlaneMake16.png")));
        iconHM.put("planeMake32", new ImageIcon(getClass().getResource("icons/PlaneMake32.png")));
        iconHM.put("showPlane16", new ImageIcon(getClass().getResource("icons/ShowPlane16.png")));
        iconHM.put("showPlane32", new ImageIcon(getClass().getResource("icons/ShowPlane32.png")));
        iconHM.put("autoFollow16", new ImageIcon(getClass().getResource("icons/AutoFollow16.png")));
        iconHM.put("autoFollow32", new ImageIcon(getClass().getResource("icons/AutoFollow32.png")));
        iconHM.put("followPlane16", new ImageIcon(getClass().getResource("icons/FollowPlane16.png")));
        iconHM.put("followPlane32", new ImageIcon(getClass().getResource("icons/FollowPlane32.png")));
        iconHM.put("followCursor16", new ImageIcon(getClass().getResource("icons/FollowCursor16.png")));
        iconHM.put("followCursor32", new ImageIcon(getClass().getResource("icons/FollowCursor32.png")));
        iconHM.put("jet16", new ImageIcon(getClass().getResource("icons/Jet16.png")));
        iconHM.put("jet32", new ImageIcon(getClass().getResource("icons/Jet32.png")));
        iconHM.put("jet74716", new ImageIcon(getClass().getResource("icons/Jet74716.png")));
        iconHM.put("jet74732", new ImageIcon(getClass().getResource("icons/Jet74732.png")));
        iconHM.put("learJet16", new ImageIcon(getClass().getResource("icons/LearJet16.png")));
        iconHM.put("learJet32", new ImageIcon(getClass().getResource("icons/LearJet32.png")));
        iconHM.put("baron5816", new ImageIcon(getClass().getResource("icons/Baron5816.png")));
        iconHM.put("baron5832", new ImageIcon(getClass().getResource("icons/Baron5832.png")));
        iconHM.put("kingAir35016", new ImageIcon(getClass().getResource("icons/KingAir35016.png")));
        iconHM.put("kingAir35032", new ImageIcon(getClass().getResource("icons/KingAir35032.png")));
        iconHM.put("cessna16", new ImageIcon(getClass().getResource("icons/Cessna16.png")));
        iconHM.put("cessna32", new ImageIcon(getClass().getResource("icons/Cessna32.png")));
        iconHM.put("cessna20816", new ImageIcon(getClass().getResource("icons/Cessna20816.png")));
        iconHM.put("cessna20832", new ImageIcon(getClass().getResource("icons/Cessna20832.png")));
        iconHM.put("beaver16", new ImageIcon(getClass().getResource("icons/Beaver16.png")));
        iconHM.put("beaver32", new ImageIcon(getClass().getResource("icons/Beaver32.png")));
        iconHM.put("dc316", new ImageIcon(getClass().getResource("icons/DC316.png")));
        iconHM.put("dc332", new ImageIcon(getClass().getResource("icons/DC332.png")));
        iconHM.put("extra16", new ImageIcon(getClass().getResource("icons/Extra16.png")));
        iconHM.put("extra32", new ImageIcon(getClass().getResource("icons/Extra32.png")));
        iconHM.put("goose16", new ImageIcon(getClass().getResource("icons/Goose16.png")));
        iconHM.put("goose32", new ImageIcon(getClass().getResource("icons/Goose32.png")));
        iconHM.put("maule16", new ImageIcon(getClass().getResource("icons/Maule16.png")));
        iconHM.put("maule32", new ImageIcon(getClass().getResource("icons/Maule32.png")));
        iconHM.put("mooney16", new ImageIcon(getClass().getResource("icons/Mooney16.png")));
        iconHM.put("mooney32", new ImageIcon(getClass().getResource("icons/Mooney32.png")));
        iconHM.put("piper16", new ImageIcon(getClass().getResource("icons/Piper16.png")));
        iconHM.put("piper32", new ImageIcon(getClass().getResource("icons/Piper32.png")));
        iconHM.put("bell16", new ImageIcon(getClass().getResource("icons/Bell16.png")));
        iconHM.put("bell32", new ImageIcon(getClass().getResource("icons/Bell32.png")));
        iconHM.put("robinson16", new ImageIcon(getClass().getResource("icons/Robinson16.png")));
        iconHM.put("robinson32", new ImageIcon(getClass().getResource("icons/Robinson32.png")));
        iconHM.put("trike16", new ImageIcon(getClass().getResource("icons/Trike16.png")));
        iconHM.put("trike32", new ImageIcon(getClass().getResource("icons/Trike32.png")));
        iconHM.put("flugzeubau16", new ImageIcon(getClass().getResource("icons/Flugzeubau16.png")));
        iconHM.put("flugzeubau32", new ImageIcon(getClass().getResource("icons/Flugzeubau32.png")));
        iconHM.put("testRadius16", new ImageIcon(getClass().getResource("icons/TestRadius16.gif")));
        iconHM.put("testRadius32", new ImageIcon(getClass().getResource("icons/TestRadius32.gif")));
        iconHM.put("airportCenter16", new ImageIcon(getClass().getResource("icons/AirportCenter16.gif")));
        iconHM.put("airportCenter32", new ImageIcon(getClass().getResource("icons/AirportCenter32.gif")));
        iconHM.put("latLon16", new ImageIcon(getClass().getResource("icons/LatLon16.gif")));
        iconHM.put("latLon32", new ImageIcon(getClass().getResource("icons/LatLon32.gif")));
        iconHM.put("find16", new ImageIcon(getClass().getResource("icons/Find16.gif")));
        iconHM.put("find32", new ImageIcon(getClass().getResource("icons/Find32.gif")));
        iconHM.put("compile16", new ImageIcon(getClass().getResource("icons/Compile16.gif")));
        iconHM.put("compile32", new ImageIcon(getClass().getResource("icons/Compile32.gif")));
        iconHM.put("prepare16", new ImageIcon(getClass().getResource("icons/Prepare16.png")));
        iconHM.put("prepare32", new ImageIcon(getClass().getResource("icons/Prepare32.png")));
        iconHM.put("errorChecking16", new ImageIcon(getClass().getResource("icons/ErrorChecking16.png")));
        iconHM.put("errorChecking32", new ImageIcon(getClass().getResource("icons/ErrorChecking32.png")));
        iconHM.put("cleanAprons16", new ImageIcon(getClass().getResource("icons/CleanAprons16.gif")));
        iconHM.put("cleanAprons32", new ImageIcon(getClass().getResource("icons/CleanAprons32.gif")));
        iconHM.put("cleanFences16", new ImageIcon(getClass().getResource("icons/CleanFences16.gif")));
        iconHM.put("cleanFences32", new ImageIcon(getClass().getResource("icons/CleanFences32.gif")));
        iconHM.put("cleanTW16", new ImageIcon(getClass().getResource("icons/CleanTW16.gif")));
        iconHM.put("cleanTW32", new ImageIcon(getClass().getResource("icons/CleanTW32.gif")));
        iconHM.put("cleanTWP16", new ImageIcon(getClass().getResource("icons/CleanTWP16.gif")));
        iconHM.put("cleanTWP32", new ImageIcon(getClass().getResource("icons/CleanTWP32.gif")));
        iconHM.put("cleanAll16", new ImageIcon(getClass().getResource("icons/CleanAll16.png")));
        iconHM.put("cleanAll32", new ImageIcon(getClass().getResource("icons/CleanAll32.png")));
        iconHM.put("karma16", new ImageIcon(getClass().getResource("icons/Karma16.png")));
        iconHM.put("karma32", new ImageIcon(getClass().getResource("icons/Karma32.png")));
        iconHM.put("helpBasics16", new ImageIcon(getClass().getResource("icons/HelpBasics16.gif")));
        iconHM.put("helpBasics32", new ImageIcon(getClass().getResource("icons/HelpBasics32.gif")));
        iconHM.put("helpBGL16", new ImageIcon(getClass().getResource("icons/HelpBGL16.gif")));
        iconHM.put("helpBGL32", new ImageIcon(getClass().getResource("icons/HelpBGL32.gif")));
        iconHM.put("helpCompile16", new ImageIcon(getClass().getResource("icons/HelpCompile16.gif")));
        iconHM.put("helpCompile32", new ImageIcon(getClass().getResource("icons/HelpCompile32.gif")));
        iconHM.put("helpConnect16", new ImageIcon(getClass().getResource("icons/HelpConnect16.png")));
        iconHM.put("helpConnect32", new ImageIcon(getClass().getResource("icons/HelpConnect32.png")));
        iconHM.put("helpSign16", new ImageIcon(getClass().getResource("icons/HelpSign16.gif")));
        iconHM.put("helpSign32", new ImageIcon(getClass().getResource("icons/HelpSign32.gif")));
        iconHM.put("helpFuel16", new ImageIcon(getClass().getResource("icons/HelpFuel16.gif")));
        iconHM.put("helpFuel32", new ImageIcon(getClass().getResource("icons/HelpFuel32.gif")));
        iconHM.put("helpBackground16", new ImageIcon(getClass().getResource("icons/HelpBackground16.gif")));
        iconHM.put("helpBackground32", new ImageIcon(getClass().getResource("icons/HelpBackground32.gif")));
        iconHM.put("helpTaxiway16", new ImageIcon(getClass().getResource("icons/HelpTaxiway16.gif")));
        iconHM.put("helpTaxiway32", new ImageIcon(getClass().getResource("icons/HelpTaxiway32.gif")));
        iconHM.put("helpApron16", new ImageIcon(getClass().getResource("icons/HelpApron16.gif")));
        iconHM.put("helpApron32", new ImageIcon(getClass().getResource("icons/HelpApron32.gif")));
        iconHM.put("helpMore16", new ImageIcon(getClass().getResource("icons/HelpMore16.gif")));
        iconHM.put("helpMore32", new ImageIcon(getClass().getResource("icons/HelpMore32.gif")));
        iconHM.put("parkingCursor", new ImageIcon(getClass().getResource("icons/ParkingCursor.gif")));
        iconHM.put("startCursor", new ImageIcon(getClass().getResource("icons/StartCursor.gif")));
        iconHM.put("towerCursor", new ImageIcon(getClass().getResource("icons/TowerCursor.gif")));
        iconHM.put("taxiPointCursor", new ImageIcon(getClass().getResource("icons/TaxiPointCursor.gif")));
        iconHM.put("ilsTaxiPointCursor", new ImageIcon(getClass().getResource("icons/ILSTaxiPointCursor.gif")));
        iconHM.put("hsTaxiPointCursor", new ImageIcon(getClass().getResource("icons/HSTaxiPointCursor.gif")));
        iconHM.put("taxiwaySignCursor", new ImageIcon(getClass().getResource("icons/TaxiwaySignCursor.gif")));
        iconHM.put("apronEdgeLightCursor", new ImageIcon(getClass().getResource("icons/ApronEdgeLightCursor.gif")));
        iconHM.put("helipadCursor", new ImageIcon(getClass().getResource("icons/HelipadCursor.gif")));
        iconHM.put("taxiwayCursor", new ImageIcon(getClass().getResource("icons/TaxiwayCursor.gif")));
        iconHM.put("apronCursor", new ImageIcon(getClass().getResource("icons/ApronCursor.gif")));
        iconHM.put("apronAddCursor", new ImageIcon(getClass().getResource("icons/ApronAddCursor.gif")));
        iconHM.put("apronDeleteCursor", new ImageIcon(getClass().getResource("icons/ApronDeleteCursor.gif")));
        iconHM.put("runwayCursor", new ImageIcon(getClass().getResource("icons/RunwayCursor.gif")));
        iconHM.put("fenceAddCursor", new ImageIcon(getClass().getResource("icons/FenceAddCursor.gif")));
        iconHM.put("fenceDeleteCursor", new ImageIcon(getClass().getResource("icons/FenceDeleteCursor.gif")));
        iconHM.put("fenceCursor", new ImageIcon(getClass().getResource("icons/FenceCursor.gif")));
        iconHM.put("blastFenceAddCursor", new ImageIcon(getClass().getResource("icons/BlastFenceAddCursor.gif")));
        iconHM.put("blastFenceDeleteCursor", new ImageIcon(getClass().getResource("icons/BlastFenceDeleteCursor.gif")));
        iconHM.put("blastFenceCursor", new ImageIcon(getClass().getResource("icons/BlastFenceCursor.gif")));
        iconHM.put("jetwayCursor", new ImageIcon(getClass().getResource("icons/JetwayCursor.gif")));
        iconHM.put("ilsBeamCursor", new ImageIcon(getClass().getResource("icons/ILSBeamCursor.gif")));
        iconHM.put("markerCursor", new ImageIcon(getClass().getResource("icons/MarkerCursor.gif")));
        iconHM.put("vorCursor", new ImageIcon(getClass().getResource("icons/VORCursor.gif")));
        iconHM.put("ndbCursor", new ImageIcon(getClass().getResource("icons/NDBCursor.gif")));
        iconHM.put("windsockCursor", new ImageIcon(getClass().getResource("icons/WindsockCursor.gif")));
        iconHM.put("excludeCursor", new ImageIcon(getClass().getResource("icons/ExcludeCursor.gif")));
        iconHM.put("fuelCursor", new ImageIcon(getClass().getResource("icons/FuelCursor.gif")));
        iconHM.put("sceneryCursor", new ImageIcon(getClass().getResource("icons/SceneryCursor.gif")));
        iconHM.put("scrollCursor", new ImageIcon(getClass().getResource("icons/ScrollCursor.gif")));
        iconHM.put("zoomInCursor", new ImageIcon(getClass().getResource("icons/ZoomInCursor.gif")));
        iconHM.put("zoomOutCursor", new ImageIcon(getClass().getResource("icons/ZoomOutCursor.gif")));
    }

    public static IconFactory getInstance()
    {
        if(factory == null)
            factory = new IconFactory();
        return factory;
    }

    public ImageIcon getIcon(String name)
    {
        if(iconHM.containsKey(name))
            return (ImageIcon)iconHM.get(name);
        else
            return null;
    }

    private HashMap iconHM;
    private static IconFactory factory = null;

}
